Enviando meu teste, tomara que esteja certo!!!
campinho-digital/repositorioTesteAula pull request #2
Opened 2022-08-02 00:41 UTC by ArleyOliveiraMendonca

Vejam se esta correto

2022-08-02 00:44 UTC, lucas-d-santos approved these changes
Eu acho que é isso kk
Boa

2022-08-02 00:54 UTC, f2lpOliveira requested changes
Atualize seu nome no 'console.log'.

2022-08-02 22:42 UTC, lucas-d-santos approved these changes
Agr sim

2022-08-03 18:27 UTC, merged

2022-08-03 18:44 UTC, carlosneves11 reviewed
Pra cimaa!